/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia;

import ControladorAcademia.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esney
 */
public class tab_estxcurso extends javax.swing.JFrame {

  conexion con=new conexion();
    Connection acade=con.Conexiondb();
     PreparedStatement ps=null;
    ResultSet rs=null;
    public tab_estxcurso() {
        initComponents();
        cargatabla();
        Cargarcombox1();
        Cargarcombox2();
    }
public void cargatabla(){
    DefaultTableModel tabla=new DefaultTableModel ();
     tabla.addColumn("Codigo Curso");
      tabla.addColumn("Documento Est.");
      tabla.addColumn("Fecha de Inicio");
     tab_estxcur.setModel(tabla);
      String datos[]=new String[3];
      tabla.addRow(datos);
      
       try {
        ps=acade.prepareStatement("SELECT * FROM tbl_estudiantexcurso");
        rs=ps.executeQuery();
        while (rs.next()){
         datos[0]=rs.getString(1);
         datos[1]=rs.getString(2);
         datos[2]=rs.getString(3); 
         tabla.addRow(datos);
        }
       } catch (Exception e) {
        System.out.print(e);
   }

}
   

    public void Registrar(){
    try{
    
    ps=acade.prepareStatement("INSERT INTO estudiantexcurso(cod_cur_estcur,doc_est_estcur,fec_ini_estcur) values (?,?,?)");
    ps.setString(1,jComboBoxcodigocurso.getSelectedItem().toString());
    ps.setString(2,jComboBoxcodigoestudiante.getSelectedItem().toString());
    ps.setString(3,jTextFieldfechainicio.getText());
  
    ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos guardados");
    }
    catch (Exception e){
    System.out.print("es " + e);
    }
}
    public void Eliminar(String dat){
        try{
        ps=acade.prepareStatement("DELETE FROM tbl_estudiantexcurso where cod_cur_estcur='"+dat+"' ");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos eliminados");
        }
            catch(Exception e){
                    System.out.print(e);
                    }
        }
    
 public void Cargarcombox1(){
    try{
        jComboBoxcodigocurso.removeAll();
        jComboBoxcodigocurso.addItem(" Seleccione Codigo ");
        ps=acade.prepareStatement("SELECT cur_cod_cur FROM  tbl_curso");
        rs=ps.executeQuery();
        while(rs.next ()){
            String aux=rs.getString("cur_cod_cur");
            this.jComboBoxcodigocurso.addItem(aux);
        }
    }
    catch(Exception e){
        
        System.out.print("eee"+e);
    }
 }
    public void Cargarcombox2(){
    try{
        jComboBoxcodigoestudiante.removeAll();
        jComboBoxcodigoestudiante.addItem("Seleccione Documento");
        ps=acade.prepareStatement("SELECT est_doc_est FROM  tbl_estudiante");
        rs=ps.executeQuery();
        while(rs.next()){
            String aux=rs.getString("est_doc_est");
            this.jComboBoxcodigoestudiante.addItem(aux);
        }
    }
    catch(Exception e){
        System.out.print("eee"+e);
    }      
    }
   public void Modificar(String cod,String doc,String  fec){
        try{
            ps=acade.prepareStatement("UPDATE tbl_estudiantexcurso SET  esc_fec_ini_estcur='"+ fec +"' , esc_doc_est_estcur='"+doc+"' where esc_doc_cur_estcur='" +cod+"' ");
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Modificados");
        }
        catch(Exception e){
            
            System.out.print( e);
        }
        
        
    } 
   
      
    
        
        
        
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab_estxcur = new javax.swing.JTable();
        jTextFieldfechainicio = new javax.swing.JTextField();
        jButtonregistrar = new javax.swing.JButton();
        jButtonmodificar = new javax.swing.JButton();
        jButtoneliminar = new javax.swing.JButton();
        jButtonlimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxcodigocurso = new javax.swing.JComboBox<>();
        jComboBoxcodigoestudiante = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tab_estxcur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tab_estxcur);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 11, 375, 275);

        jTextFieldfechainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldfechainicioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldfechainicio);
        jTextFieldfechainicio.setBounds(538, 111, 100, 20);

        jButtonregistrar.setText("regidtrar");
        jButtonregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonregistrar);
        jButtonregistrar.setBounds(393, 179, 77, 23);

        jButtonmodificar.setText("modificar");
        jButtonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonmodificar);
        jButtonmodificar.setBounds(488, 179, 77, 23);

        jButtoneliminar.setText("eliminar");
        jButtoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoneliminar);
        jButtoneliminar.setBounds(583, 179, 71, 23);

        jButtonlimpiar.setText("limpiar");
        jButtonlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonlimpiar);
        jButtonlimpiar.setBounds(393, 220, 65, 23);

        jLabel1.setText("codigo curso");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(405, 35, 60, 14);

        jLabel2.setText("codigo estudiante");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(405, 75, 85, 14);

        jLabel3.setText("fecha inicio");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(405, 114, 53, 14);

        jComboBoxcodigocurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(jComboBoxcodigocurso);
        jComboBoxcodigocurso.setBounds(538, 31, 100, 22);

        getContentPane().add(jComboBoxcodigoestudiante);
        jComboBoxcodigoestudiante.setBounds(538, 71, 100, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Academia_de_San_Carlos_esquina_de_Calle_de_Moneda_y_Academia.JPG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 670, 300);

        jMenu1.setText("             programas");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("profesor");
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("estudiante");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("curso");
        jMenu1.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldfechainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldfechainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldfechainicioActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jButtonregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistrarActionPerformed
        Registrar();
       cargatabla();
    }//GEN-LAST:event_jButtonregistrarActionPerformed

    private void jButtonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodificarActionPerformed
         String cod,doc,fec;
        cod=jComboBoxcodigocurso.getSelectedItem().toString();
        doc=jComboBoxcodigoestudiante.getSelectedItem().toString();
        fec=jTextFieldfechainicio.getText();
        Modificar(cod, doc, fec);
        cargatabla();
    }//GEN-LAST:event_jButtonmodificarActionPerformed

    private void jButtoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneliminarActionPerformed
         String dat=jComboBoxcodigocurso.getSelectedItem().toString();        
        Eliminar(dat);
       cargatabla();
    }//GEN-LAST:event_jButtoneliminarActionPerformed

    private void jButtonlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlimpiarActionPerformed
        jComboBoxcodigocurso.removeAllItems();
        jComboBoxcodigoestudiante.removeAllItems();
        Cargarcombox1();
        Cargarcombox2();
        jTextFieldfechainicio.setText(null);
    }//GEN-LAST:event_jButtonlimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tab_estxcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tab_estxcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tab_estxcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tab_estxcurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tab_estxcurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoneliminar;
    private javax.swing.JButton jButtonlimpiar;
    private javax.swing.JButton jButtonmodificar;
    private javax.swing.JButton jButtonregistrar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JComboBox<String> jComboBoxcodigocurso;
    private javax.swing.JComboBox<String> jComboBoxcodigoestudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldfechainicio;
    private javax.swing.JTable tab_estxcur;
    // End of variables declaration//GEN-END:variables
}
