/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia;

import ControladorAcademia.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esney
 */
public class tab_estudiante extends javax.swing.JFrame {

   conexion con=new conexion();
    Connection acade=con.Conexiondb();
     PreparedStatement ps=null;
    ResultSet rs=null;
    public tab_estudiante() {
        initComponents();
        cargatabla();
    }
public void cargatabla(){
    DefaultTableModel tabla=new DefaultTableModel ();
    tabla.addColumn("Documento");
      tabla.addColumn("Nombre ");
      tabla.addColumn("Apellido");
      tabla.addColumn("Edad");
      tab_estudiante.setModel(tabla);
      String dato[]=new String[4];
      
       try {
        ps=acade.prepareStatement("SELECT * FROM tbl_estudiante");
        rs=ps.executeQuery();
        while (rs.next()){
         dato[0]=rs.getString(1);
         dato[1]=rs.getString(2);
         dato[2]=rs.getString(3);
         dato[3]=rs.getString(4);  
         tabla.addRow(dato);
        }
       } catch (Exception e) {
        System.out.print(e);
   }
   }
 public void Registrar(){
    try{
    ps=acade.prepareStatement("INSERT INTO tbl_estudiante(est_doc_est, est_nom_est, est_ape_est, est_edad_est) values (?,?,?,?)");
    ps.setInt(1,Integer.parseInt(jTextDocumento.getText()));
    ps.setString(2,jTextNombre.getText());
    ps.setString(3,jTextFApellidp.getText());
    ps.setInt(4,Integer.parseInt(jTextEdad.getText()));
    ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos guardados");
    }
    catch (Exception e){
    System.out.print("es " + e);
    }

 }
    public void Eliminar(String dat){
        try{
        ps=acade.prepareStatement("DELETE FROM tbl_estudiante where  est_doc_est='"+dat+"' ");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos eliminados");
        }
            catch(Exception e){
                    System.out.print(e);
                    }
     }
    
 public void modificar ( String doc ,String nom,String apelli,String edad  ){
     try {
       ps=acade.prepareStatement(" UPDATE tbl_estudiante  set est_nom_est='"+nom+"', est_ape_est='"+apelli+"', est_edad_est='"+edad+"', where est_doc_est="+doc+" ");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "datos modificados");
     } catch (Exception e) {
         System.out.println("eee"+e);
     }
 
 
 
 }   
 
  public void limpiar (String dat){
  try {
   ps=acade.prepareStatement("DELETE from tbl_estudiante  where  est_doc_est='"+dat+"'");
      ps.executeUpdate();
      JOptionPane.showMessageDialog(null,"Datos Eliminados");
        } catch (Exception e) {
             System.out.println("eee"+e);
        }
    
      
  
  }
    
    
   public void filtro(){
        DefaultTableModel tabla=new DefaultTableModel();
        
        tabla.addColumn("Documento");
        tabla.addColumn("Nombre");
        tabla.addColumn("Apellido");
        tabla.addColumn("edar");
        
        
       tab_estudiante.setModel(tabla);
        String datos[]=new String[4];
        
        try {
            ps=acade.prepareStatement("SELECT * FROM tbl_estudiante  where est_doc_est like '%"+jTextFieldfiltrar.getText()+"%'");
            rs=ps.executeQuery();
            while (rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                
                tabla.addRow(datos);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    public void listardatos(){
    int lis=tab_estudiante.getSelectedRow();
    if(lis>=0){
  
    jTextDocumento.setText(tab_estudiante.getValueAt(lis,0).toString());
    jTextNombre.setText(tab_estudiante.getValueAt(lis,1).toString());
    jTextFApellidp.setText(tab_estudiante.getValueAt(lis,2).toString());
    jTextEdad.setText(tab_estudiante.getValueAt(lis,3).toString());
   
    
    }
    
    
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_estudiante = new javax.swing.JTable();
        jTextDocumento = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextFApellidp = new javax.swing.JTextField();
        jTextEdad = new javax.swing.JTextField();
        jButtoneliminar = new javax.swing.JButton();
        jButtonrequitrar = new javax.swing.JButton();
        jButtonlimpiado = new javax.swing.JButton();
        jTextFieldfiltrar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tab_estudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tab_estudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_estudianteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_estudiante);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 89, 567, 190);
        getContentPane().add(jTextDocumento);
        jTextDocumento.setBounds(81, 22, 76, 20);
        getContentPane().add(jTextNombre);
        jTextNombre.setBounds(222, 22, 90, 20);
        getContentPane().add(jTextFApellidp);
        jTextFApellidp.setBounds(389, 22, 106, 20);
        getContentPane().add(jTextEdad);
        jTextEdad.setBounds(541, 22, 36, 20);

        jButtoneliminar.setText("eliminar");
        jButtoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoneliminar);
        jButtoneliminar.setBounds(167, 48, 71, 23);

        jButtonrequitrar.setText("reguistrar");
        jButtonrequitrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrequitrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonrequitrar);
        jButtonrequitrar.setBounds(18, 48, 81, 23);

        jButtonlimpiado.setText("limpiar");
        jButtonlimpiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlimpiadoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonlimpiado);
        jButtonlimpiado.setBounds(322, 48, 65, 23);

        jTextFieldfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldfiltrarActionPerformed(evt);
            }
        });
        jTextFieldfiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldfiltrarKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldfiltrar);
        jTextFieldfiltrar.setBounds(230, 300, 80, 20);

        jButton5.setText("modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(413, 48, 77, 23);

        jLabel1.setText("documento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 25, 53, 14);

        jLabel2.setText("nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(167, 25, 45, 14);

        jLabel3.setText("apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(322, 25, 49, 14);

        jLabel4.setText("edad");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(513, 25, 24, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Academia_de_San_Carlos_esquina_de_Calle_de_Moneda_y_Academia.JPG"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 590, 340);

        jMenu1.setText("tablas");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("estudiante por curso");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("profesor");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("curso");
        jMenu1.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonrequitrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrequitrarActionPerformed
     Registrar();
     cargatabla();
    }//GEN-LAST:event_jButtonrequitrarActionPerformed

    private void jButtoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneliminarActionPerformed
         String  dat=jTextDocumento.getText();
        
        Eliminar(dat);
        cargatabla();
    }//GEN-LAST:event_jButtoneliminarActionPerformed

    private void jButtonlimpiadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlimpiadoActionPerformed
        jTextDocumento.setText(null);
        jTextEdad.setText(null);
        jTextFApellidp.setText(null);
        jTextNombre.setText(null);        
        
        
    }//GEN-LAST:event_jButtonlimpiadoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String doc,nom,apelli,edad;
        
        doc=jTextDocumento.getText();
        nom=jTextNombre.getText();
        apelli=jTextFApellidp.getText();
        edad=jTextEdad.getText();
        
        modificar(doc, nom, apelli, edad);
        cargatabla();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        tab_estxcurso ec=new tab_estxcurso();
       ec.setVisible(true);
       dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        tab_profesor p=new tab_profesor();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jTextFieldfiltrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldfiltrarKeyReleased
        // TODO add your handling code here:
        filtro();
    }//GEN-LAST:event_jTextFieldfiltrarKeyReleased

    private void jTextFieldfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldfiltrarActionPerformed
        
    }//GEN-LAST:event_jTextFieldfiltrarActionPerformed

    private void tab_estudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_estudianteMouseClicked
        listardatos();
    }//GEN-LAST:event_tab_estudianteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tab_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tab_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tab_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tab_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tab_estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtoneliminar;
    private javax.swing.JButton jButtonlimpiado;
    private javax.swing.JButton jButtonrequitrar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextDocumento;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextFApellidp;
    private javax.swing.JTextField jTextFieldfiltrar;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTable tab_estudiante;
    // End of variables declaration//GEN-END:variables
}
