
package academia;

import ControladorAcademia.conexion;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esney
 */
public class tab_profesor extends javax.swing.JFrame {
  conexion con=new conexion();
    Connection acade=con.Conexiondb();
     PreparedStatement ps=null;
    ResultSet rs=null;
    
    public tab_profesor() {
        initComponents();
        cargatabla();
    }
 public void cargatabla(){
    DefaultTableModel tabla=new DefaultTableModel ();
        tabla.addColumn("Documento");
        tabla.addColumn("Nombre");
        tabla.addColumn("Apellido");
        tabla.addColumn("Categoria");
        tabla.addColumn("Salario");
        tabla.addColumn("Clave");
        profesor.setModel(tabla);
        String datos[]=new String[6];
        
        try{
        ps=acade.prepareStatement("SELECT *FROM tbl_Profesor");
         rs=ps.executeQuery();
         while (rs.next()){
           datos[0]=rs.getString(1);
           datos[1]=rs.getString(2);
           datos[2]=rs.getString(3);
           datos[3]=rs.getString(4);
           datos[4]=rs.getString(5);
           datos[5]=rs.getString(6);
           tabla.addRow(datos);
         }
        } catch (Exception e) {
            System.out.print(e);
        }
}
 
 public void registrar(){
  try {
          ps=acade.prepareStatement("insert into tbl_profesor (pro_doc_prof,pro_nom_prof,pro_cate_prof,por_ape_prof,pro_sal_prof,clave) values ( ?,?,?,?,?,?) ");
          ps.setInt (1,Integer.parseInt(jTextFielddocumento.getText()));
          ps.setString(2,jTextFieldnombre.getText() );
          ps.setInt(3,Integer.parseInt(jTextFieldcategoria.getText()));
          ps.setString(4,jTextFieldapellido.getText());
          ps.setInt(5,Integer.parseInt(jTextFieldsalario.getText()));
          ps.setInt(6,Integer.parseInt(jTextFieldclave.getText()));
          ps.executeUpdate();
          
          JOptionPane.showMessageDialog(null,"Datos guardado");                  
                  
                  
           } catch (Exception e) {
               System.out.print("eee"+e);
           
           }
  
  
 }
 
 public void modificar ( String doc,String nom,String apelli ,String catego,String salari,String clav){
     try {
         
         ps=acade.prepareStatement(" UPDATE  tbl_profesor set pro_nom_prof='"+nom+"',por_ape_prof='"+apelli+"',pro_cate_prof='"+catego+"',pro_sal_prof='"+salari+"',clave="+clav+" where pro_doc_prof="+doc+" ");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "datos modificados");
     
     } catch (Exception e) {
         System.out.println("eee"+e);
                 
     }
 
 
 }
 
 public void Eliminar(String dat){
    try {
   ps=acade.prepareStatement("DELETE from tbl_profesor where pro_doc_prof='"+dat+"'");
      ps.executeUpdate();
      JOptionPane.showMessageDialog(null,"Datos Eliminados");
        } catch (Exception e) {
             System.out.println("eee"+e);
        }
    
    } 
 
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        profesor = new javax.swing.JTable();
        jTextFielddocumento = new javax.swing.JTextField();
        jTextFieldnombre = new javax.swing.JTextField();
        jTextFieldcategoria = new javax.swing.JTextField();
        jButtonregistrar = new javax.swing.JButton();
        jTextFieldapellido = new javax.swing.JTextField();
        jTextFieldsalario = new javax.swing.JTextField();
        jTextFieldclave = new javax.swing.JTextField();
        jButtonmodificar = new javax.swing.JButton();
        jButtoneliminar = new javax.swing.JButton();
        jButtonlimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();

        jLabel1.setText("jLabel1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        profesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(profesor);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 656, 230);

        jTextFielddocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddocumentoActionPerformed(evt);
            }
        });
        jTextFielddocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFielddocumentoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFielddocumento);
        jTextFielddocumento.setBounds(133, 11, 88, 20);

        jTextFieldnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnombreKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldnombre);
        jTextFieldnombre.setBounds(133, 49, 88, 20);

        jTextFieldcategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldcategoriaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldcategoria);
        jTextFieldcategoria.setBounds(133, 82, 88, 20);

        jButtonregistrar.setText("registrar");
        jButtonregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonregistrar);
        jButtonregistrar.setBounds(22, 113, 75, 23);

        jTextFieldapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldapellidoActionPerformed(evt);
            }
        });
        jTextFieldapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldapellidoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldapellido);
        jTextFieldapellido.setBounds(395, 11, 99, 20);

        jTextFieldsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsalarioActionPerformed(evt);
            }
        });
        jTextFieldsalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldsalarioKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldsalario);
        jTextFieldsalario.setBounds(395, 49, 99, 20);

        jTextFieldclave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldclaveKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldclave);
        jTextFieldclave.setBounds(395, 82, 99, 20);

        jButtonmodificar.setText("modificar");
        jButtonmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonmodificar);
        jButtonmodificar.setBounds(182, 113, 77, 23);

        jButtoneliminar.setText("eliminar");
        jButtoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoneliminar);
        jButtoneliminar.setBounds(351, 113, 71, 23);

        jButtonlimpiar.setText("limpiar");
        jButtonlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonlimpiar);
        jButtonlimpiar.setBounds(527, 113, 65, 23);

        jLabel2.setText("Documento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(37, 14, 60, 14);

        jLabel3.setText("nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(37, 41, 60, 14);

        jLabel4.setText("categoria");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(37, 85, 60, 14);

        jLabel5.setText("apellido");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(319, 17, 36, 14);

        jLabel6.setText("salario");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(324, 52, 31, 14);

        jLabel7.setText("clave");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 87, 25, 14);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Academia_de_San_Carlos_esquina_de_Calle_de_Moneda_y_Academia.JPG"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 670, 380);

        jMenu1.setText("tablas");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("curso");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("estudiante");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("estudiante por curso");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistrarActionPerformed
        registrar();
        cargatabla();
    }//GEN-LAST:event_jButtonregistrarActionPerformed

    private void jTextFielddocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddocumentoActionPerformed

    private void jTextFieldsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsalarioActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        tab_estudiante es=new tab_estudiante();
        es.setVisible(true);
        dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jTextFielddocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFielddocumentoKeyTyped
    char c=evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();

        }
    }//GEN-LAST:event_jTextFielddocumentoKeyTyped

    private void jTextFieldnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnombreKeyTyped
      char c=evt.getKeyChar();
        if (Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldnombreKeyTyped

    private void jTextFieldcategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcategoriaKeyTyped
        char c=evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldcategoriaKeyTyped

    private void jTextFieldapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldapellidoActionPerformed
       
        
    }//GEN-LAST:event_jTextFieldapellidoActionPerformed

    private void jTextFieldapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldapellidoKeyTyped
         char b=evt.getKeyChar();
        if (Character.isDigit(b)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldapellidoKeyTyped

    private void jTextFieldsalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldsalarioKeyTyped
        char b=evt.getKeyChar();
        if (!Character.isDigit(b)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldsalarioKeyTyped

    private void jTextFieldclaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldclaveKeyTyped
        char b=evt.getKeyChar();
        if (!Character.isDigit(b)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldclaveKeyTyped

    private void jButtonmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodificarActionPerformed
     String doc,n,p,ca,sa,cl;
     doc=jTextFielddocumento.getText();
     n=jTextFieldnombre.getText();
     p=jTextFieldapellido.getText();
     ca=jTextFieldcategoria.getText();
     sa=jTextFieldsalario.getText();
     cl=jTextFieldclave.getText();
      
     modificar(doc,n,p,ca,sa,cl);
     cargatabla();
            
    }//GEN-LAST:event_jButtonmodificarActionPerformed

    private void jButtoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneliminarActionPerformed
        String dat=jTextFielddocumento.getText();
        Eliminar(dat);
        cargatabla();
    }//GEN-LAST:event_jButtoneliminarActionPerformed

    private void jButtonlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlimpiarActionPerformed
        jTextFieldapellido.setText(null);
        jTextFieldsalario.setText(null);
        jTextFieldnombre.setText(null);
        jTextFieldclave.setText(null);
        jTextFielddocumento.setText(null);
        jTextFieldcategoria.setText(null);
                
    }//GEN-LAST:event_jButtonlimpiarActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        tab_curso cu=new tab_curso();
        cu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
       tab_estxcurso ec=new tab_estxcurso();
       ec.setVisible(true);
       dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tab_profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tab_profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tab_profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tab_profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tab_profesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoneliminar;
    private javax.swing.JButton jButtonlimpiar;
    private javax.swing.JButton jButtonmodificar;
    private javax.swing.JButton jButtonregistrar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldapellido;
    private javax.swing.JTextField jTextFieldcategoria;
    private javax.swing.JTextField jTextFieldclave;
    private javax.swing.JTextField jTextFielddocumento;
    private javax.swing.JTextField jTextFieldnombre;
    private javax.swing.JTextField jTextFieldsalario;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable profesor;
    // End of variables declaration//GEN-END:variables
}
